# Generated by Django 5.2.10 on 2026-02-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # operations = [
    #     migrations.CreateModel(
    #         # name='Vendor',
            # fields=[
            #     ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            #     ('name', models.CharField(max_length=255)),
            # ],
            # options={
            #     'verbose_name': 'Vendor',
            #     'verbose_name_plural': 'Vendors',
            #     'db_table': 'vendor',
            # },
    #     ),
    # ]
